declare const DEFAULT_META_TRANSACTION_BLOCK_HEIGHT_TTL = 100n;
declare const MAX_GAS = 300000000000000n;
declare const PAGODA_RPC_ENDPOINTS_MAINNET: string[];
declare const PAGODA_RPC_ARCHIVAL_ENDPOINTS_MAINNET: string[];
declare const PAGODA_RPC_ENDPOINTS_TESTNET: string[];
declare const PAGODA_RPC_ARCHIVAL_ENDPOINTS_TESTNET: string[];
declare const KITWALLET_FUNDED_TESTNET_ACCOUNT_ENDPOINT = "https://testnet-api.kitwallet.app/account";

export { DEFAULT_META_TRANSACTION_BLOCK_HEIGHT_TTL, KITWALLET_FUNDED_TESTNET_ACCOUNT_ENDPOINT, MAX_GAS, PAGODA_RPC_ARCHIVAL_ENDPOINTS_MAINNET, PAGODA_RPC_ARCHIVAL_ENDPOINTS_TESTNET, PAGODA_RPC_ENDPOINTS_MAINNET, PAGODA_RPC_ENDPOINTS_TESTNET };
